[screen]
width = 450
height = 630

[frame]
delay = 0.01

[player]
speed = 10
bullet_speed = 3
attack_interval = 20
invincible_time = 300

[enemy]
born_interval = 300
speed = 1
bullet_speed = 2
attack_interval = 100
